Try moving matrix logic up a level for correct dependencies between jobs

diff --git a/.github/workflows/disseminate.yml b/.github/workflows/disseminate.yml
--- a/.github/workflows/disseminate.yml
+++ b/.github/workflows/disseminate.yml
@@ -5,9 +5,9 @@ name: disseminate
 on:
   workflow_call:
     inputs:
-      work-ids:
-        required: true
-        type: string
+      # work-ids:
+      #   required: true
+      #   type: string
       platform:
         required: true
         type: string
@@ -17,10 +17,10 @@ jobs:
     runs-on: ubuntu-latest
     # container:
     #   image: openbookpublishers/thoth-dissemination:latest
-    strategy:
-      fail-fast: false
-      matrix:
-        work-id: ${{ fromJSON(inputs.work-ids) }}
+    # strategy:
+    #   fail-fast: false
+    #   matrix:
+    #     work-id: ${{ fromJSON(inputs.work-ids) }}
     steps:
       - name: Make all platform credentials available to later steps (with names lowercased)
         uses: oNaiPs/secrets-to-env-action@v1.5
@@ -30,18 +30,18 @@ jobs:
 
       - name: Run disseminator using Dockerhub image
         run: |
-          if [ ${{matrix.work-id}} == "1" ]; then
+          if [ ${{inputs.work-id}} == "1" ]; then
             exit 1
           else
-            echo "this is a location" >> ${{ matrix.work-id }}
+            echo "this is a location" >> ${{ inputs.work-id }}
           fi
 
       - name: Upload output to artifact
         uses: actions/upload-artifact@v4
         if: contains(fromJSON('["InternetArchive", "CUL", "Figshare", "Zenodo"]'), inputs.platform)
         with:
-          name: ${{ matrix.work-id }}
-          path: ${{ matrix.work-id }}
+          name: ${{ inputs.work-id }}
+          path: ${{ inputs.work-id }}
           retention-days: 1
           if-no-files-found: ignore
           overwrite: false
@@ -49,19 +49,20 @@ jobs:
   write-locations:
     runs-on: ubuntu-latest
     needs: disseminate
-    if: (success() || failure()) && contains(fromJSON('["InternetArchive", "CUL", "Figshare", "Zenodo"]'), inputs.platform)
-    strategy:
-      fail-fast: false
-      matrix:
-        work-id: ${{ fromJSON(inputs.work-ids) }}
+    # if: (success() || failure()) && contains(fromJSON('["InternetArchive", "CUL", "Figshare", "Zenodo"]'), inputs.platform)
+    if: contains(fromJSON('["InternetArchive", "CUL", "Figshare", "Zenodo"]'), inputs.platform)
+    # strategy:
+    #   fail-fast: false
+    #   matrix:
+    #     work-id: ${{ fromJSON(inputs.work-ids) }}
     steps:
       - name: Download disseminator output artifact containing location info
         uses: actions/download-artifact@v4
         with:
-          name: ${{ matrix.work-id }}
+          name: ${{ inputs.work-id }}
 
       - name: Fake outcome
-        run: echo ${{ matrix.work-id }}
+        run: echo ${{ inputs.work-id }}
 
       # - name: Checkout
       #   uses: actions/checkout@v4
@@ -75,7 +76,7 @@ jobs:
       #   run: pip install -r requirements_write_locations.txt
 
       # - name: Write locations to Thoth using Python script
-      #   run: python write_locations.py ${{ matrix.work-id }}
+      #   run: python write_locations.py ${{ inputs.work-id }}
       #   env:
       #     THOTH_EMAIL: ${{ secrets.THOTH_EMAIL }}
       #     THOTH_PWD: ${{ secrets.THOTH_PWD }}
